port 6380
bind 127.0.0.1
protected-mode yes

dbfilename redis-store.rdb
appendfilename store-store.aof

appendonly yes
appendfsync everysec
no-appendfsync-on-rewrite yes

save 900 1
save 300 10
save 60 10000

maxmemory 4gb
maxmemory-policy noeviction

requirepass changemeplease
